/*
The MIT License

Copyright (c) 2014- High-Mobility GmbH (https://high-mobility.com)

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

#ifndef HMKIT_CORE_CERT_H_
#define HMKIT_CORE_CERT_H_

#include <stdint.h>
#include "hmkit_core_api.h"

#define HMKIT_CORE_CERT_VER_0 0x00
#define HMKIT_CORE_CERT_VER_1 0x01

#define HMKIT_CORE_CERT_VERSION_SIZE                1
#define HMKIT_CORE_CERT_ISSUER_SIZE                 4
#define HMKIT_CORE_CERT_SERIAL_SIZE                 9
#define HMKIT_CORE_CERT_DATE_SIZE                   5
#define HMKIT_CORE_CERT_SIGNATURE_SIZE              64
#define HMKIT_CORE_CERT_PUBLIC_KEY_SIZE             64
#define HMKIT_CORE_CERT_PERMISSION_SIZE_BYTE_SIZE   1
#define HMKIT_CORE_CERT_JOURNEY_ID_SIZE				6

#define HMKIT_CORE_CERT_AUTO_API_PERMISSIONS_ID		0x10
#define HMKIT_CORE_CERT_CAR_RENTAL_PERMISSIONS_ID	0x20


//Certificate V0

#define HMKIT_CORE_CERT_V0_MIN_SIZE 157
#define HMKIT_CORE_CERT_V0_MAX_SIZE 173
#define HMKIT_CORE_CERT_V0_MAX_PERMISSIONS_SIZE 16

#define HMKIT_CORE_CERT_V0_GAINING_SERIAL_POSITION      0
#define HMKIT_CORE_CERT_V0_GAINING_PUBLIC_KEY_POSITION  HMKIT_CORE_CERT_SERIAL_SIZE
#define HMKIT_CORE_CERT_V0_PROVIDING_SERIAL_POSITION    HMKIT_CORE_CERT_SERIAL_SIZE + HMKIT_CORE_CERT_PUBLIC_KEY_SIZE
#define HMKIT_CORE_CERT_V0_START_DATE_POSITION          HMKIT_CORE_CERT_SERIAL_SIZE + HMKIT_CORE_CERT_PUBLIC_KEY_SIZE + HMKIT_CORE_CERT_SERIAL_SIZE
#define HMKIT_CORE_CERT_V0_END_DATE_POSITION            HMKIT_CORE_CERT_SERIAL_SIZE + HMKIT_CORE_CERT_PUBLIC_KEY_SIZE + HMKIT_CORE_CERT_SERIAL_SIZE + HMKIT_CORE_CERT_DATE_SIZE
#define HMKIT_CORE_CERT_V0_PERMISSIONS_SIZE_POSITION    HMKIT_CORE_CERT_SERIAL_SIZE + HMKIT_CORE_CERT_PUBLIC_KEY_SIZE + HMKIT_CORE_CERT_SERIAL_SIZE + HMKIT_CORE_CERT_DATE_SIZE + HMKIT_CORE_CERT_DATE_SIZE
#define HMKIT_CORE_CERT_V0_PERMISSIONS_POSITION         HMKIT_CORE_CERT_SERIAL_SIZE + HMKIT_CORE_CERT_PUBLIC_KEY_SIZE + HMKIT_CORE_CERT_SERIAL_SIZE + HMKIT_CORE_CERT_DATE_SIZE + HMKIT_CORE_CERT_DATE_SIZE + HMKIT_CORE_CERT_PERMISSION_SIZE_BYTE_SIZE

//Certificate V1

#define HMKIT_CORE_CERT_V1_MIN_SIZE 162
#define HMKIT_CORE_CERT_V1_MAX_SIZE 178
#define HMKIT_CORE_CERT_V1_MAX_PERMISSIONS_SIZE 16

#define HMKIT_CORE_CERT_V1_VERSION_POSITION             0
#define HMKIT_CORE_CERT_V1_ISSUER_POSITION              HMKIT_CORE_CERT_VERSION_SIZE
#define HMKIT_CORE_CERT_V1_PROVIDING_SERIAL_POSITION    HMKIT_CORE_CERT_VERSION_SIZE + HMKIT_CORE_CERT_ISSUER_SIZE
#define HMKIT_CORE_CERT_V1_GAINING_SERIAL_POSITION      HMKIT_CORE_CERT_VERSION_SIZE + HMKIT_CORE_CERT_ISSUER_SIZE + HMKIT_CORE_CERT_SERIAL_SIZE
#define HMKIT_CORE_CERT_V1_GAINING_PUBLIC_KEY_POSITION  HMKIT_CORE_CERT_VERSION_SIZE + HMKIT_CORE_CERT_ISSUER_SIZE + HMKIT_CORE_CERT_SERIAL_SIZE + HMKIT_CORE_CERT_SERIAL_SIZE
#define HMKIT_CORE_CERT_V1_START_DATE_POSITION          HMKIT_CORE_CERT_VERSION_SIZE + HMKIT_CORE_CERT_ISSUER_SIZE + HMKIT_CORE_CERT_SERIAL_SIZE + HMKIT_CORE_CERT_SERIAL_SIZE + HMKIT_CORE_CERT_PUBLIC_KEY_SIZE
#define HMKIT_CORE_CERT_V1_END_DATE_POSITION            HMKIT_CORE_CERT_VERSION_SIZE + HMKIT_CORE_CERT_ISSUER_SIZE + HMKIT_CORE_CERT_SERIAL_SIZE + HMKIT_CORE_CERT_SERIAL_SIZE + HMKIT_CORE_CERT_PUBLIC_KEY_SIZE + HMKIT_CORE_CERT_DATE_SIZE
#define HMKIT_CORE_CERT_V1_PERMISSIONS_SIZE_POSITION    HMKIT_CORE_CERT_VERSION_SIZE + HMKIT_CORE_CERT_ISSUER_SIZE + HMKIT_CORE_CERT_SERIAL_SIZE + HMKIT_CORE_CERT_SERIAL_SIZE + HMKIT_CORE_CERT_PUBLIC_KEY_SIZE + HMKIT_CORE_CERT_DATE_SIZE + HMKIT_CORE_CERT_DATE_SIZE
#define HMKIT_CORE_CERT_V1_PERMISSIONS_POSITION         HMKIT_CORE_CERT_VERSION_SIZE + HMKIT_CORE_CERT_ISSUER_SIZE + HMKIT_CORE_CERT_SERIAL_SIZE + HMKIT_CORE_CERT_SERIAL_SIZE + HMKIT_CORE_CERT_PUBLIC_KEY_SIZE + HMKIT_CORE_CERT_DATE_SIZE + HMKIT_CORE_CERT_DATE_SIZE + HMKIT_CORE_CERT_PERMISSION_SIZE_BYTE_SIZE

#define HMKIT_CORE_CERT_V1_CAR_RENT_BOOK_ID_OFFSET		10 // from the start of permissions

#define HMKIT_CORE_CERT_MAX_SIZE HMKIT_CORE_CERT_V1_MAX_SIZE

uint8_t hmkit_core_cert_print(uint8_t *cert);
uint8_t hmkit_core_cert_get_size(uint8_t *cert, uint16_t *size);
uint8_t hmkit_core_cert_get_as_bytes( hmkit_core_certificate_t *certificate, uint8_t *cert, uint16_t *size);
uint8_t hmkit_core_cert_get_as_struct(uint8_t *cert, hmkit_core_certificate_t *certificate);
uint8_t hmkit_core_cert_get_journeyId(uint8_t *cert, uint8_t *pjourneyId);

#endif /* HMKIT_CORE_CERT_H_ */
